<?php
/* config.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/* database info */

$db_servername = 'localhost';
$db_username = '${app.name?lower_case?replace(" ","_")}';
$db_password = 'changethis';
$db_name = '${app.name?lower_case?replace(" ","_")}';
$db_prefix = '${app.name?lower_case?replace(" ","_")}_';


/* application info */

$sa_appname = "${app.name}"; //application name


/* item labels */

$item_labels = array();
<#list app.items as item>
$item_labels['${item.name}'] = '${item.label}';
</#list>


/* role rights */

$allowed_items = array();
<#list app.roles as role>
$allowed_items['${role.name}'] = array(<#list role.allowed_items as allowed_item>'${allowed_item}'<#sep>,</#list>);
</#list>

$creatable_items = array();
<#list app.roles as role>
$creatable_items['${role.name}'] = array(<#list role.creatable_items as creatable_item>'${creatable_item}'<#sep>,</#list>);
</#list>

$editable_items = array();
<#list app.roles as role>
$editable_items['${role.name}'] = array(<#list role.editable_items as editable_item>'${editable_item}'<#sep>,</#list>);
</#list>

$deletable_items = array();
<#list app.roles as role>
$deletable_items['${role.name}'] = array(<#list role.deletable_items as deletable_item>'${deletable_item}'<#sep>,</#list>);
</#list>

?>
