<?php
/* change-password.php */
$error = "";
include('user-rights.php');
include('sa-functions.php');
include('sa-login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>
  <title>
    ${app.name} - Change Password
  </title>
  <link rel="stylesheet" type="text/css" href="css/style.css">
 </head>
 <body>

 <h1>
    ${app.name} - Change Password </h1>
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	?>
	<div id="items">
	Logged as <?php echo $loggedInUser; ?>, <a href="sa-logout.php">Logout</a>
	<?php if ($is_primary) { ?> | <a href="settings.php">Settings</a> <?php } ?>
	| Change Password
	<h2><a href="index.php">Home</a> > Change Password</h2>

<?php
$cpwd_message = '';
if (isset($_POST['submit']) && 'changePassword'==$_POST['action']) {
	if (empty($_POST['newPassword']) || empty($_POST['confirmPassword'])) {
  		$cpwd_message = "Password cannot be empty!";
	} else {
		$newPassword=$_POST['newPassword'];
		$confirmPassword=$_POST['confirmPassword'];
		$newPassword = stripslashes($newPassword);
		$confirmPassword = stripslashes($confirmPassword);

		if ($newPassword == $confirmPassword) {
			if (updatePassword($loggedInUser,$newPassword)) {
				$cpwd_message = "Password has been changed.";
			} else {
				$cpwd_message = "Unable to change the password.";
			}
		} else {
			$cpwd_message = "Passwords are not equal.";
		}
	}
}
?>

<div id="login">
<form action="" method="post">
<input id="action" name="action" value="changePassword" type="hidden">
<table>
<tr>
<td>
<label>New Password :</label>
</td>
<td>
<input id="newPassword" name="newPassword" placeholder="**********" type="password"><br/>
</td>
</tr>
<tr>
<td>
<label>Confirm Password :</label>
</td>
<td>
<input id="confirmPassword" name="confirmPassword" placeholder="**********" type="password"><br/>
</td>
</tr>
<table>
<input name="submit" type="submit" value=" Change "><br/>
<span><?php echo $cpwd_message; ?></span>
</form>
</div>

	</div>
	<?php
} else {
	include('sa-login-form.php');
}
?>
<div id="footer">
Generated by AppsoFluna
</div>
 </body>
</html>
