<?php
/* index.php */
$error = "";
include('user-rights.php');
include('sa-functions.php');
include('sa-login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>
  <title>
    ${app.name}
  </title>
  <link rel="stylesheet" type="text/css" href="css/style.css">
 </head>
 <body>

 <h1>
    ${app.name}
 </h1>
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	?>
	<div id="items">
	Logged as <?php echo $loggedInUser; ?>, <a href="sa-logout.php">Logout</a>
	<?php if ($is_primary) { ?> | <a href="settings.php">Settings</a> <?php } ?>
	| <a href="change-password.php">Change Password</a>
	<h2>Menu</h2>
	<ul>

	<?php
	$rolename = getRoleByUsername($loggedInUser);
	$var_items = getAllowedItemsByRole($rolename);
	foreach ($var_items as $item) {
		?>
		<li><a href="list/<?php echo $item; ?>.php"><?php echo getItemLabel($item); ?></a></li>
		<?php
	}
	?>
	</ul>
	</div>
	<?php
} else {
	include('sa-login-form.php');
}
?>
<div id="footer">
Generated by AppsoFluna
</div>
 </body>
</html>
