<#function titleCase text>
  <#local len = text?length />
  <#if (len>1)>
    <#return text[0]?upper_case + text[1..]> 
  <#else>
    <#return text?upper_case>
  </#if>
</#function>
<?php
/* list/${item.name}.php */
$error = "";
include('../user-rights.php');
include('../sa-functions.php');
include('../sa-login.php');
$is_logged_in = isset($_SESSION['login_user']);

function getAll${titleCase(item.name)}Records() {
	global $db_prefix;
	$conn = getConnection();
	if (!$conn) {
		return null;
	}

	$sql = "SELECT id<#list item.fields as field>, ${field.name}<#if field.type == 'period'>_from, ${field.name}_to</#if><#if field.type == 'item'>_id</#if></#list> FROM ".$db_prefix."${item.name}";
	$result = mysqli_query($conn, $sql);

	$all_${item.name}_records = array();
	if ($result && mysqli_num_rows($result) > 0) {
		while($row = mysqli_fetch_assoc($result)) {
			<#list item.fields as field>
			<#if field.type == 'item'>
				$ref_${field.name}_id = $row['${field.name}_id'];
				if ($ref_${field.name}_id) {
					$ref_${field.name}_sql = "SELECT <#list field.extra.refFields as refField>${refField}<#sep>,</#list> FROM ".$db_prefix."${field.extra.refItem} WHERE id = $ref_${field.name}_id";
					$ref_${field.name}_result = mysqli_query($conn,$ref_${field.name}_sql);
					if ($ref_${field.name}_result && mysqli_num_rows($ref_${field.name}_result) > 0 && $ref_${field.name}_row = mysqli_fetch_assoc($ref_${field.name}_result)) {
						$${field.name}_label = <#list field.extra.refFields as refField>$ref_${field.name}_row['${refField}']<#sep>.' '.</#list>;
						$row['${field.name}_label'] = $${field.name}_label;
					} else {
						$row['${field.name}_label'] = '';
					}
				} else {
					$row['${field.name}_label'] = '';
				}
			</#if>
			</#list>
			$all_${item.name}_records[] = $row;
		}
	}
	mysqli_close($conn);

	return $all_${item.name}_records;
}

?>

<html>
 <head>
  <title>
	${app.name} - ${item.label} Records
  </title>
  <link rel="stylesheet" type="text/css" href="../css/style.css">
 </head>
 <body>
<h1>
	${app.name} - ${item.label} Records
</h1>
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	$rolename = getRoleByUsername($loggedInUser);

	$is_allowed = isItemAllowed('${item.name}',$rolename);
	$is_creatable = isItemCreatable('${item.name}',$rolename);
	$is_editable = isItemEditable('${item.name}',$rolename);
	$is_deletable = isItemDeletable('${item.name}',$rolename);
		?>

		<div id="items">
		Logged as <?php echo $loggedInUser; ?>, <a href="../sa-logout.php">Logout</a>
		<?php if ($is_primary) { ?> | <a href="../settings.php">Settings</a> <?php } ?>
		| <a href="../change-password.php">Change Password</a>
		<h2><a href="../index.php">Home</a> > ${titleCase(item.label)} Records</h2>
<?php
	if ($is_allowed) {
?>
		<?php if ($is_creatable) { ?> <a href="../single/${item.name}.php?page=create">Create New</a> <?php }
		?>
		<table>
			<thead>
				<tr>
					<#list item.fields as field>
					<td>${field.label}</td>
					</#list>
					<td><?php if ($is_editable) echo "#"; ?></td>
				</tr>
			</thead>
			<tbody>
			<?php
			$records = getAll${titleCase(item.name)}Records();
			foreach ($records as $record) {
				?>
				<tr>
					<#list item.fields as field>
					  <td><?php echo $record["${field.name}<#if field.type == 'period'>_from"];
                                                    echo ' - ';
                                                    echo $record["${field.name}_to</#if><#if field.type == 'item'>_label</#if>"]; ?></td>
					</#list>
				  <td>
					<?php if ($is_editable) { ?> <a href="../single/${item.name}.php?page=edit&id=<?php echo $record['id']; ?>">edit</a>
					<?php 
					      if ($is_deletable) echo "|";
					}
					if ($is_deletable) { ?>
				    		<a href="../single/${item.name}.php?page=delete&id=<?php echo $record['id']; ?>">delete</a>
					<?php } ?>
				  </td>
				</tr>
			<?php } ?>
			<tbody>
		</table>
		</div>
		<?php
	} else {
		?>
		This page is restricted.
		<?php
	}
} else {
	include('../sa-login-form.php');
}
?>
<div id="footer">
Generated by AppsoFluna
</div>
 </body>
</html>
