<?php
/* change-password.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

$relative_path = "./";
include($relative_path.'functions.php');
include($relative_path.'login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>

<?php include($relative_path."preheaders.php"); ?>
  <title>
    <?php echo $sa_appname; ?> - Change Password
  </title>
<?php include($relative_path."headers.php"); ?>
 </head>
 <body>

<div id="main" class="container" role="main">
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	?>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $relative_path; ?>index.php"><?php echo $sa_appname; ?></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Change Password</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Logged as <?php echo $loggedInUser; ?></a></li>
      <li><a href="<?php echo $relative_path; ?>logout.php">Logout</a></li>
      <?php if ($is_primary) { ?><li><a href="<?php echo $relative_path; ?>users.php">Users</a></li><?php } ?>

	<li><a href="#"></a></li>
    </ul>
  </div>
</nav>


<?php
		$formMessage = '';
		$formStatus = "info";
if (isset($_POST['submit']) && 'changePassword'==$_POST['action']) {
	if (empty($_POST['newPassword']) || empty($_POST['confirmPassword'])) {
  		$formMessage = "Password cannot be empty!";
		$formStatus = "danger";
	} else {
		$newPassword=$_POST['newPassword'];
		$confirmPassword=$_POST['confirmPassword'];
		$newPassword = stripslashes($newPassword);
		$confirmPassword = stripslashes($confirmPassword);

		if ($newPassword == $confirmPassword) {
			if (updatePassword($loggedInUser,$newPassword)) {
				$formMessage = "Password has been changed.";
				$formStatus = "success";
			} else {
				$formMessage = "Unable to change the password.";
				$formStatus = "danger";
			}
		} else {
			$formMessage = "Passwords are not equal.";
			$formStatus = "danger";
		}
	}
}
?>
<form action="" method="post" role="form">

<?php

if ($formMessage && strlen($formMessage)>0) {
?>
<div class="alert alert-<?php echo $formStatus; ?>">
  <?php echo $formMessage; ?>
</div>
<?php } ?>

<input id="action" name="action" value="changePassword" type="hidden">
<div class="form-group">
	<label for="newPassword">New password</label>
	<input class="form-control"  id="newPassword" name="newPassword" placeholder="**********" type="password">
</div>
<div class="form-group">
	<label for="confirmPassword">Confirm password</label>
	<input class="form-control"  id="confirmPassword" name="confirmPassword" placeholder="**********" type="password">
</div>
<input class="btn btn-default" name="submit" type="submit" value="Change">
</form>
	<?php
} else {
	include($relative_path.'login-form.php');
}

include($relative_path.'footer.php');
?>
</div>
 </body>
</html>
