<?php
/* headers.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

if (!isset($relative_path)) $relative_path = "";
?>
<link rel="stylesheet" type="text/css" href="<?php echo $relative_path; ?>css/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $relative_path; ?>css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $relative_path; ?>css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $relative_path; ?>css/datatables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $relative_path; ?>css/style.css">
<script src="<?php echo $relative_path; ?>js/jquery.js"></script>
<script src="<?php echo $relative_path; ?>js/jquery-ui.min.js"></script>
<script src="<?php echo $relative_path; ?>js/jquery.datatables.min.js"></script>
<script src="<?php echo $relative_path; ?>js/bootstrap.min.js"></script>
<script src="<?php echo $relative_path; ?>js/datatables.bootstrap.min.js"></script>


