<?php
/* index.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

$relative_path="./";
include($relative_path.'functions.php');
include($relative_path.'login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>

<?php include($relative_path."preheaders.php"); ?>
  <title>
    <?php echo $sa_appname; ?>
  </title>
<?php include($relative_path."headers.php"); ?>
 </head>
 <body>
<div id="main" class="container" role="main">
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	?>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><?php echo $sa_appname; ?></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Logged as <?php echo $loggedInUser; ?></a></li>
      <li><a href="<?php echo $relative_path; ?>logout.php">Logout</a></li>
      <?php if ($is_primary) { ?><li><a href="<?php echo $relative_path; ?>users.php">Users</a></li><?php } ?>
      <li><a href="<?php echo $relative_path; ?>change-password.php">Change Password</a></li>
	<li><a href="#"></a></li>
    </ul>
  </div>
</nav>
	<div id="items">
	<ul class="nav nav-pills nav-stacked">

	<?php
	$rolename = getRoleByUsername($loggedInUser);
	$var_items = getAllowedItemsByRole($rolename);
	foreach ($var_items as $item) {
		?>
		<li><a href="<?php echo $relative_path; ?>list/<?php echo $item; ?>.php"><?php echo getItemLabel($item); ?></a></li>
		<?php
	}
	?>
	</ul>
	</div>
	<?php
} else { 
	include($relative_path.'login-form.php');
}
include($relative_path.'footer.php');
?>
<div/>
 </body>
</html>
