<?php
/* login-form.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

?>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><?php echo $sa_appname; ?></a>
    </div>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Login</a></li>
    </ul>
  </div>
</nav>
<?php
if ($error && strlen($error)>0) {
?>
<div class="alert alert-danger">
  <?php echo $error; ?>
</div>
<?php } ?>
<div id="login">
<form action="" method="post" role="form">
<input id="action" name="action" value="login" type="hidden">
<div class="form-group">
<label for="username">Username</label>
<input class="form-control" id="username" name="username" placeholder="username" type="text">
</div>
<div class="form-group">
<label for="password">Password</label>
<input class="form-control" id="password" name="password" placeholder="**********" type="password">
</div>
<input name="submit" class="btn btn-default" type="submit" value="Login">
</form>
</div>
