<?php
/* users.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

$relative_path="./";
include($relative_path.'functions.php');
include($relative_path.'login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>

<?php include($relative_path."preheaders.php"); ?>
  <title>
	<?php echo $sa_appname; ?> - Users
  </title>
<?php include($relative_path."headers.php"); ?>

  <script>
$(document).ready(function() {
    $('#tbl_data').DataTable();
} );
  </script>
 </head>
 <body>
<div id="main" class="container" role="main">
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);
	if ($is_primary) {
		?>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $relative_path; ?>index.php"><?php echo $sa_appname; ?></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Users</a></li>
        <li><a href="<?php echo $relative_path; ?>user.php?page=create">Create New</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Logged as <?php echo $loggedInUser; ?></a></li>
      <li><a href="<?php echo $relative_path; ?>logout.php">Logout</a></li>
      <li><a href="<?php echo $relative_path; ?>change-password.php">Change Password</a></li>
      <li><a href="#"></a></li>
    </ul>
  </div>
</nav>
		<table id="tbl_data" class="table table-striped table-bordered" cellspacing="0" width="100%">
			<thead>
				<tr>
					<td>Username</td>
					<td>Rolename</td>
					<td>Primary</td>
					<td>#</td>
				</tr>
			</thead>
			<tbody>
			<?php
			$users = getAllUsers();
			foreach ($users as $user) {
				?>
				<tr>
				  <td><?php echo $user["username"]; ?></td>
				  <td><?php echo $user["rolename"]; ?></td>
				  <td><?php echo $user["primary"]; ?></td>
				  <td>
				    <a class="btn btn-default"  href="<?php echo $relative_path; ?>user.php?page=edit&id=<?php echo $user['id']; ?>">edit</a>
				    <a class="btn btn-default"  href="<?php echo $relative_path; ?>user.php?page=delete&id=<?php echo $user['id']; ?>">delete</a>
				  </td>
				</tr>
			<?php } ?>
			<tbody>
		</table>
		<?php
	} else {
		?>
		You are not allowed to change settings.
		<?php
	}
} else {
	include($relative_path.'login-form.php');
}
include($relative_path.'footer.php');
?>
</div>
 </body>
</html>
