<?php
/* index.php */
/* Generated by AppsoFluna */

/*
 * Copyright (c) Charaka Gunatillake / AppsoFluna. (http://www.appsofluna.com)
 * All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

$relative_path="./";
include($relative_path.'functions.php');
include($relative_path.'login.php');
$is_logged_in = isset($_SESSION['login_user']);
?>

<html>
 <head>

<?php include($relative_path."preheaders.php"); ?>
  <title>
	<?php echo $sa_appname; ?> - User
  </title>
<?php include($relative_path."headers.php"); ?>
 </head>
 <body>
<div id="main" class="container" role="main">
<?php
if ($is_logged_in) {
	$loggedInUser = $_SESSION['login_user'];
	$is_primary = isPrimaryByUsername($loggedInUser);

	if ($is_primary) {
		$page = "view";
		$user_id = null;
		$user = null;
		$page_edit = false;
		$page_delete = false;
		$page_create = false;
		$formMessage = '';
		$formStatus = "info";

		if (isset($_GET['page'])) {
			$page = $_GET['page'];
			if ($page=="create") {
				$page_create = true;
			}
		}

		if (isset($_GET['id'])) {
			if ($page_create) {
				$page_create=false;
			} else {
				$user_id = $_GET['id'];
				if ($user = getUserById($user_id)) {

					if ($page=="edit") {
						$page_edit = true;
					} else if ($page=="delete") {
						$page_delete = true;
					} 
				}
			}
		}

		if ($page_edit || $page_delete || $page_create) {
			$roles = getAllRoles();
			if (isset($_POST['submit'])) {
				if ($page_edit && 'editUser'==$_POST['action']) {
					if (empty($_POST['rolename']) || empty($_POST['primary'])) {
						$formMessage = "Invalid values.";
						$formStatus = "danger";
					} else {
						$rolename=$_POST['rolename'];
						$primary=$_POST['primary'];
						$rolename = stripslashes($rolename);
						$primary = stripslashes($primary);
                                                if ($primary=="no" && $user['username']==$loggedInUser) {
                                                    $formMessage = "The active user cannot be change to a non-primary user.";
	 					$formStatus = "danger";
                                                } else if (updateUser($user_id,$rolename,$primary)) {
							$user = getUserById($user_id);
							$formMessage = "The user has been updated.";
							$formStatus = "success";
						} else {
							$formMessage = "Unable to update the user.";
							$formStatus = "danger";
						}
					}
				}
				if ($page_delete && 'deleteUser'==$_POST['action']) {
					if ($user['username']==$loggedInUser) {
						$formMessage = "The active user cannot be removed.";
						$formStatus = "danger";
					} else if(deleteUserById($user_id)) {
						$formMessage = "The user has been deleted.";
						$formStatus = "success";
						header("Location: settings.php");
					} else {
						$formMessage = "Unable to delete the user.";
						$formStatus = "danger";
					}			
				}
				if ($page_create && 'createUser'==$_POST['action']) {
					if (empty($_POST['username']) || empty($_POST['rolename']) || empty($_POST['primary'])) {
						$formMessage = "Invalid values.";
						$formStatus = "danger";
					} else {
						$username=$_POST['username'];
						$password=$_POST['password'];
						$rolename=$_POST['rolename'];
						$primary=$_POST['primary'];
						$username = stripslashes($username);
						$password = stripslashes($password);
						$rolename = stripslashes($rolename);
						$primary = stripslashes($primary);
						if (createUser($username,$password,$rolename,$primary)) {
							$formMessage = "The user has been created.";
							$formStatus = "success";
							header("Location: settings.php");
						} else {
							$formMessage = "Unable to create the user.";
							$formStatus = "danger";
						}
					}		
				}
			} else if ($page_create) {
				$user = array();
				$user['username'] = '';
				$user['password'] = '';
				$user['rolename'] = '';
				$user['primary'] = 'no';
			}
			?>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $relative_path; ?>index.php"><?php echo $sa_appname; ?></a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="<?php echo $relative_path; ?>users.php">Users</a></li>
        <li class="active"><a href="#"><?php
								if ($user_id) {
									echo $user['username'];
								} else {
									echo "Create New";
								} ?></a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Logged as <?php echo $loggedInUser; ?></a></li>
      <li><a href="<?php echo $relative_path; ?>logout.php">Logout</a></li>
      <li><a href="<?php echo $relative_path; ?>change-password.php">Change Password</a></li>
      <li><a href="#"></a></li>
    </ul>
  </div>
</nav>

<form action="" method="post"  role="form">
<?php
$pageAction = "";
$formVisible = false;
if ($page_edit) {
	$formVisible = true;
	$submitLabel = "Update";
	$pageAction = "editUser";
} else if ($page_delete) {
	$formVisible = true;
	$submitLabel = "Delete";
	$pageAction = "deleteUser";
} else if ($page_create) {
	$formVisible = true;
	$submitLabel = "Create";
	$pageAction = "createUser";
}
if ($formMessage && strlen($formMessage)>0) {
?>
<div class="alert alert-<?php echo $formStatus; ?>">
  <?php echo $formMessage; ?>
</div>
<?php } ?>
<input id="action" name="action" value="<?php echo $pageAction ?>" type="hidden">

<div class="form-group">
	<label for="username">Username</label>
							<?php if ($page_create) { ?>
								<input class="form-control" id="username" type="text" name="username" value="<?php echo $user['username']; ?>" />
							<?php } else { ?>
								<fieldset id="username"><?php echo $user['username']; ?></fieldset>
							<?php } ?>
</div>
<div class="form-group">
	<label for="password">Password</label>
	<?php if ($page_create) { ?>
								<input class="form-control" id="password" name="password" placeholder="**********" type="password" value="<?php echo $user['password']; ?>">
							<?php } else { ?>
								<fieldset id="password">**********</fieldset>
							<?php } ?>
</div>
<div class="form-group">
	<label for="rolename">Rolename</label>
	<?php if ($page_edit || $page_create) { ?>
								<select class="form-control" id="rolename" name="rolename" >
								<?php 
									foreach ($roles as $role) {
									?>
									  <option <?php if ($user['rolename']==$role) echo 'selected="selected"'; ?>
										value="<?php echo $role; ?>">
										<?php echo $role; ?>
									  </option>
									<?php
									}
								?>
								</select>
							<?php } else { ?>
								<fieldset id="rolename"><?php echo $user['rolename']; ?></fieldset>
							<?php } ?>
</div>
<div class="form-group">
	<label for="primary">Primary</label>
			<?php if ($page_edit || $page_create) { ?>
								<select class="form-control" id="primary" name="primary">
									<option <?php if ($user['primary']=='yes') echo 'selected="selected"'; ?>
										value="yes">
										Yes
									</option>
									<option <?php if ($user['primary']=='no') echo 'selected="selected"'; ?>
										value="no">
										No
									</option>
								</select>
							<?php } else { ?>
								<fieldset id="primary"><?php echo $user['primary']; ?></fieldset>
							<?php } ?>
</div>
<?php if ($formVisible) { ?>
<input name="submit" class="btn btn-default" type="submit" value="<?php echo $submitLabel; ?>">
<?php } ?>
</form>

			<?php
		}
	} else {
		?>
		This page is restricted.
		<?php
	}
} else {
	include($relative_path.'login-form.php');
}
include($relative_path.'footer.php');
?>
</div>
 </body>
</html>
